# Generated by Django 3.0.1 on 2020-03-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_auto_20200308_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='HOME.Doctor'),
            preserve_default=False,
        ),
    ]
