# Generated by Django 3.0.1 on 2020-03-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
