# Generated by Django 3.0.1 on 2020-03-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0005_complaint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Signature',
            field=models.ImageField(default=0, upload_to='Signature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='phoneno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
