# Generated by Django 3.0.1 on 2020-03-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0006_auto_20200314_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
