# Generated by Django 3.0.1 on 2020-03-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0008_complaint_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='id',
        ),
        migrations.AddField(
            model_name='prescription',
            name='complaint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HOME.Complaint'),
            preserve_default=False,
        ),
    ]
